name: Autograding Tests

on: [push, pull_request]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Run Gradle Tests
      id: gradle-test
      run: ./gradlew test

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        test-results: ${{ steps.gradle-test.outputs.result }}
