name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Compile Java Code
      run: |
        mkdir -p target/classes
        mkdir -p target/test-classes
        if [ -d "src/main/java" ]; then
          javac -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" -d target/classes $(find src/main/java -name "*.java")
        fi

    - name: Compile Test Code
      run: |
        if [ -d "src/test" ]; then
          javac -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:target/classes" -d target/test-classes $(find src/test -name "*.java")
        fi

    - name: Run Tests
      run: |
        if [ -d "src/test" ]; then
          java -cp "target/test-classes:target/classes:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore $(find src/test -name "*Test.java" | sed 's/src\/test\/java\///' | sed 's/\//./g' | sed 's/.java//')
        fi
